# Generated by Django 6.0.2 on 2026-02-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CELERY', 'Celery'), ('GLUTEN', 'Gluten'), ('CRUSTACEANS', 'Crustaceans'), ('EGGS', 'Eggs'), ('FISH', 'Fish'), ('LUPINES', 'Lupines'), ('MILK', 'Milk/Dairy'), ('MUSTARD', 'Mustard'), ('NUTS', 'Tree Nuts'), ('PEANUTS', 'Peanuts'), ('SESAME', 'Sesame'), ('SOYA', 'Soya'), ('SULPHATES', 'Sulphates')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Allergy',
                'verbose_name_plural': 'Allergies',
            },
        ),
    ]
