# Generated by Django 6.0.2 on 2026-02-19 10:40

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('COFFEE', 'Coffee'), ('TEA', 'Tea'), ('NONALCOHOLIC', 'Nonalcoholic'), ('MOCKTAILS', 'Mocktails'), ('JUICE', 'Juice'), ('BEER', 'Beer'), ('ALCOHOLIC', 'Alcoholic'), ('COCKTAIL', 'Cocktail'), ('SPIRIT', 'Spirit'), ('APERITIF', 'Aperitif'), ('DIGESTIF', 'Digestif'), ('LIQUEUR', 'Liqueur'), ('FERMENTED', 'Fermented'), ('SAKE', 'Sake')], default='NONALCOHOLIC', max_length=50)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[common.validators.RangeValidator(0, 1000, message='Price must be between 0 and 100000')])),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='drinks_images/', validators=[common.validators.FileSizeValidator(max_mb=5)])),
                ('publishing_date', models.DateField()),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('allergies', models.ManyToManyField(blank=True, related_name='drinks', to='common.allergy')),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('RED', 'Red'), ('WHITE', 'White'), ('ROSE', 'Rosé'), ('SPARK', 'Sparkling'), ('FORT', 'Fortified'), ('DESSERT', 'Dessert')], default='RED', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[common.validators.RangeValidator(0, 1000, message='Price must be between 0 and 1000')])),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='wines_images/', validators=[common.validators.FileSizeValidator(max_mb=5)])),
                ('publishing_date', models.DateField()),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('allergies', models.ManyToManyField(blank=True, related_name='wines', to='common.allergy')),
            ],
        ),
    ]
