# Generated by Django 6.0.2 on 2026-02-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image_mimetype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
