# Generated by Django 6.0.2 on 2026-02-23 10:48

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_wine_image_mimetype_alter_wine_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='image_mimetype',
        ),
        migrations.AlterField(
            model_name='wine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[common.validators.FileSizeValidator(max_mb=5)]),
        ),
    ]
