# Generated by Django 6.0.2 on 2026-02-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_remove_wine_image_mimetype_alter_wine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
