# Generated by Django 6.0.2 on 2026-02-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('STARTER', 'Starter'), ('MAIN', 'Main'), ('DESSERT', 'Dessert'), ('snacks', 'Snacks')], default='snacks', max_length=50),
        ),
    ]
